<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 *
 * MODAL OPTIMIZED TEMPLATE
 * Optimized for display inside modal windows
 * Removes large header, reduces padding, optimized for narrow widths
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;

// Create shortcuts to some parameters.
$params  = $this->item->params;
$images  = json_decode($this->item->images);
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = Factory::getUser();
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
$currentDate   = Factory::getDate()->format('Y-m-d H:i:s');
$isUnpublished = ($this->item->state == 0 || $this->item->publish_up > $currentDate
	|| (($this->item->publish_down < $currentDate) && $this->item->publish_down !== Factory::getDbo()->getNullDate()));

$htag    = $this->params->get('show_page_heading') ? 'h2' : 'h1';

?>

<style>
/* ================================================================
   MODAL OPTIMIZED STYLES
   ================================================================ */

.container.t3-mainbody {
	max-width: 100% !important;
	overflow-x: hidden;
	padding: 0 !important;
}

.item-page {
	padding: 0 !important;
	margin: 0 !important;
}

/* Minimal hidden header for modal (10px padding mobile only) */
.modal-minimal-header {
	padding: 10px 15px 0 15px;
}

@media (min-width: 768px) {
	.modal-minimal-header {
		padding: 15px 20px 0 20px;
	}
}

.modal-minimal-header h1 {
	font-size: 1.5rem;
	font-weight: 600;
	margin: 0 0 10px 0;
	line-height: 1.3;
}

/* Article content spacing for modal */
.article-content {
	padding: 10px 15px 20px 15px;
}

@media (min-width: 768px) {
	.article-content {
		padding: 15px 25px 25px 25px;
	}
}

/* Terms and conditions checkbox responsive width */
@media (max-width: 767px) {
	.vrc-terms-block {
		width: 95% !important;
		margin: 0 auto;
		padding: 10px 0;
	}
}

/* Remove extra margins and padding for modal display */
.page-header {
	margin: 0 !important;
	padding: 0 !important;
	border: 0 !important;
}

/* Fix scrolling inside modal */
body.modal-open .item-page {
	overflow-y: auto;
	-webkit-overflow-scrolling: touch;
}

#ar-header {
    display: none;
}

.fancybox-slide {
    padding: 0 !important;
}

</style>

<div class="item-page<?php echo $this->pageclass_sfx . $this->item->state ? ' item-is-unpublished' : ''; ?>" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? Factory::getConfig()->get('language') : $this->item->language; ?>">

	<!-- Minimal Modal Header (10px padding mobile) -->
	<div class="modal-minimal-header">
		<h1><?php echo $this->escape($this->item->title); ?></h1>
	</div>

	<?php if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative) {
		echo $this->item->pagination;
	}
	?>

	<?php // Content is generated by content plugin event onContentAfterTitle ?>
	<?php echo $this->item->event->afterDisplayTitle; ?>

	<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
		<?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
	<?php endif; ?>

	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php echo LayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags); ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event onContentBeforeDisplay ?>
	<?php echo $this->item->event->beforeDisplayContent; ?>

	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position', '0') == '0' && empty($urls->urls_position)))
		|| (empty($urls->urls_position) && (!$params->get('urls_position')))) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>

	<?php if ($params->get('access-view')) : ?>
	<?php if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) : ?>
		<?php echo $this->item->pagination; ?>
	<?php endif; ?>

	<?php if (isset ($this->item->toc)) : ?>
		<?php echo $this->item->toc; ?>
	<?php endif; ?>

	<div itemprop="articleBody" class="article-content">
		<?php echo $this->item->text; ?>
	</div>

	<?php if ($info == 1 || $info == 2) : ?>
		<?php if ($useDefList) : ?>
				<?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
		<?php endif; ?>
		<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
			<?php echo LayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags); ?>
		<?php endif; ?>
	<?php endif; ?>

	<?php if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && !$this->item->paginationrelative) : ?>
		<?php echo $this->item->pagination; ?>
	<?php endif; ?>

	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position', '0') == '1'))) : ?>

	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>

	<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
	<?php echo LayoutHelper::render('joomla.content.intro_image', $this->item); ?>
	<?php echo HTMLHelper::_('content.prepare', $this->item->introtext); ?>
	<?php // Optional link to let them register to see the whole article. ?>
	<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
	<?php $menu = Factory::getApplication()->getMenu(); ?>
	<?php $active = $menu->getActive(); ?>
	<?php $itemId = $active->id; ?>
	<?php $link = new Uri(Route::_('index.php?option=com_users&view=login&ItemId=' . $itemId, false)); ?>
	<?php $link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
	<p class="readmore">
		<a href="<?php echo $link; ?>" class="btn btn-primary">
			<?php $attribs = json_decode($this->item->attribs); ?>
			<?php
			if ($attribs->alternative_readmore == null) {
				echo Text::_('COM_CONTENT_REGISTER_TO_READ_MORE');
			} elseif ($readmore = $this->item->alternative_readmore) {
				echo $readmore;
				if ($params->get('show_readmore_title', 0) != 0) {
					echo HTMLHelper::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
				}
			} elseif ($params->get('show_readmore_title', 0) == 0) {
				echo Text::sprintf('COM_CONTENT_READ_MORE_TITLE');
			} else {
				echo Text::_('COM_CONTENT_READ_MORE');
				echo HTMLHelper::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
			}
			?>
		</a>
	</p>
	<?php endif; ?>
	<?php endif; ?>

	<?php if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && $this->item->paginationrelative) : ?>
	<?php echo $this->item->pagination; ?>
	<?php endif; ?>

	<?php echo $this->item->event->afterDisplayContent; ?>
</div>